= La bibliothèque streams

== Streams
* Un _flux_ (_stream_) est une séquence d'éléments
* Il véhicule des éléments à partir d'une source à travers un _pipeline_
* Un flux ne stocke aucune donnée
** ce n'est pas une structure de données

== Pipeline
* Un pipeline est une séquence d'opérations applicables sur un flux
* Il comporte
** une source (collection, tableau, fonction génératrice, flux I/O)
** une séquence d'opérations intermédiaires (chacune produit un nouveau stream)
** une opération terminale qui calcule un résultat
* Une opération ne modifie pas le flux d'origine
* L'évaluation est _paresseuse_
* Peut être exécuté séquentiellement ou en parallèle

== Opération terminale
* Une opération terminal traverse le flux pour produire un résultat ou un effet de bord
* Après exécution, le flux est considéré comme consommé et ne peut pas être réutilisé
* Une opération terminale est également nommée _réduction_

== Un exemple de stream

[source,java,indent=0]
----
List<Integer> numbers = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);

// Calcul le total des doubles des nombres pairs
System.out.println(
    numbers.stream()
           .filter(e -> e % 2 == 0)
           .mapToInt(e -> e * 2)
           .sum());
----

== L'interface `Stream`
* L'interface https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html[`java.util.stream.Stream`] regroupe l'ensemble des opérations applicables aux pipelines
* Les interfaces `IntStream`, `LongStream` et `DoubleStream` sont spécialisées pour les types primitifs

== Création d'un flux
* À partir d'une collection
** `Collection.stream`, `Collection.parallelStream` (flux parallèle)
* À partir d'un tableau (`Arrays.stream`)
* À partir d'un intervalle
** `IntStream.range`, `IntStream.rangeClosed` (aussi avec `LongStream`)
* À partir de valeurs
** `Stream.of` (aussi dans `IntStream`, `LongStream` et `DoubleStream`)
* À partir des méthodes de classe de `Stream`
** `concat`, `empty`, `generate`/`iterate` (flux infini)
* À partir de nombres aléatoires (`doubles`, `ints` et `longs` de la classe `Random`)
* À partir d'un fichier (`Files.lines`, `BufferedReader.lines`)

== Quelques opérations intermédiaires
[options="header"]
|===
| Opération | Description

| `filter` | retourne les éléments respectant un prédicat

| `map` | applique une fonction à chaque élément

| `flatMap` | désimbrique des flux

| `limit` | tronque un flux

| `skip` | ignore les premiers éléments

| `distinct` | élimine les doublons (avec état)

| `sorted` | retourne un flux trié (avec état)

|===

== Opérations intermédiaires (exemples)

[source,java,indent=0]
----
List<Integer> numbers = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);

numbers.stream()
       .filter(e -> e % 2 == 0)
       .forEach(System.out::println)); // 2 4 6 8 10

numbers.stream()
       .filter(e -> e % 2 == 0)
       .map(e -> e * 2)
       .forEach(System.out::println)); // 4 8 12 16 20
----

== Quelques opérations terminales
[options="header"]
|===
| Opération | Description

| `reduce` | applique une réduction avec une fonction d'accumulation

| `count` | compte les éléments

| `sum`, ... | réduction spécialisée sur les flux de types primitifs

| `collect` | réalise une réduction par modification

| `allMatch` | teste si tous les éléments respectent un prédicat

| `forEach` | exécute une action pour chaque élément

|===

== Opérations terminales (exemple) 1/3

.Calculer une somme avec `reduce`
[source,java,indent=0]
----
List<Integer> numbers = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);

System.out.println(
    numbers.stream()
           .filter(e -> e % 2 == 0)
           .map(e -> e * 2.0)
           .reduce(0.0, (carry, e) -> carry + e));
----

.Calculer une somme avec `sum` et `DoubleStream`
[source,java,indent=0]
----
System.out.println(
    numbers.stream()
           .filter(e -> e % 2 == 0)
           .mapToDouble(e -> e * 2.0)
           .sum());
----

== Opérations terminales (exemple) 2/3

.Les doubles des nombres pairs dans une liste avec `collect`
[source,java,indent=0]
----
List<Integer> numbers = Arrays.asList(1, 2, 3, 4, 5, 1, 2, 3, 4, 5);

List<Integer> doubleOfEven =
    numbers.stream()
           .filter(e -> e % 2 == 0)
           .map(e -> e * 2)
           .collect(Collectors.toList());
System.out.println(doubleOfEven);
----

.Les doubles des nombres pairs dans un dictionnaire avec `collect`
[source,java,indent=0]
----
Map<Integer, Integer> doubleOfEven =
    numbers.stream()
           .filter(e -> e % 2 == 0)
           .collect(Collectors.toMap(
               Function.identity(),
               i -> i * 2));
System.out.println(doubleOfEven);
----

== Opérations terminales (exemple) 3/3

.Un dictionnaire des personnes regroupées par nom
[source,java,indent=0]
----
List<Person> persons = //...

Map<Person, List<Person>> personsByName =
    persons.stream()
           .collect(Collectors.groupingBy(Person::getName));
System.out.println(personsByName);
----

.Un dictionnaire des noms de personnes regroupés par sexe
[source,java,indent=0]
----
Map<Person.Gender, List<String>> namesByGender =
    persons.stream()
           .collect(Collectors.groupingBy(
               Person::getGender,
               Collectors.mapping(
                   Person::getName,
                   Collectors.toList())));
----

== Flux infinis
* Les méthodes de classe `Stream.generate` et `Stream.iterate` créent un flux infini
* Ce type de flux peut exister grâce à l'_évaluation paresseuse_
** l'application d'opérations élémentaires ne provoque pas la traversée du pipeline
** seules les opérations terminales déclenchent le traitement

.Un dictionnaire des noms de personnes regroupés par sexe
[source,java,indent=0]
----
Stream<Integer> integers = Stream.iterate(0, i -> i + 1);
integers.limit(10)
        .forEach(System.out::println);
----

WARNING: Il ne faut jamais réduire l'intégralité d'un flux infini.

